### ISSUE TITLE
Composition API first Class support

### ISSUE THREAD

**Issue by Xenoha** [vuejs/vue-test-utils-next#876] opened 2021-08-20 19:47 UTC
Hello Team, 

This has been a great suite through the evolution of Vue, However, I feel like with this being a RC, there seems to be a lot of working around happening for simple Vue3 components. The documentation doesn't offer much for testing when using the compositions API and with the release of the setup SFC from the vue team this utils seems even further behind.

I'm not trying to be a bad news bear but I am dealing with a lot of issues which I would think should be first class with a test utils. At the very least, can the docs be updated to show composition api examples for each case?

1. When using the globals.provide with the mount method, the values can be brought into a component as proxies or variable depending on how the user provides them in the parent. This isn't handled well inside the current mount method and when accessing an injected variable with the `myVariable.value` the test utils seems to no longer track correctly.

2. The same occurs when bringing in props. Props are usually defined now through `defineProps`, and the user has the change to destructure with `toRefs` or use the prop itself. As soon as the user uses the property with `toRefs` the user is dealing with a proxy that the suite just doesn't handle.

The below highlights a simple example: (Just to highlight my thoughts above ) 
We have a simple component that renders the provided prop `title`. Then based on `title` and the injected `type` we grab some kind of data and set the ref `data` with the new data array.

```vue
<template>
  <div>
    {{ title }}
  </div>
  <div v-if="data.length" id="data">
    Has Data
  </div>
</template>
```

```vue
<script setup>
import { toRefs, ref, inject } from "vue";

const props = defineProps({
	title: { required: true, type: String },
});

const { title } = toRefs(props);

const type = inject("parentType"); // proxy`

const data = ref([]);

function getData() {
	 // get data based on the title and type.value then set it to data.value.
	 // data.value = newData
}

getData();
</script>
```

I would love your assistance here, but I don't see a way to test the template for the `div#data` element? I don't have a first class way to: `expect(wrapper.find('#data').exists()).toBe(true)`.

To start _I think_  I would have to:

```js
const mockGetData = jest.fn()
global.provide = { parentType: 'something' }
```

Then type.value wouldn't exist because the utils doesn't handle this case, correct? Moreover, checking title.value in the setup won't have a value because I would provide props of `title: 'Some Title'`. 

Using the composition API, how do I toggle the ref `data`? How do I both check the template text and do some calculation of the provided prop `title`? How do I toggle and add data to data.value?

Again, I have loved your tools and love what you did with the global.provide, teleport, and emitted() implementations. I just feel it's time we see first class support for the Composition API with clear documentation in a release candidate for Vue3.

As Always, assistance is always accepted.

**Comment by cexbrayat** [comment] 2021-08-23 08:08
Hi @Xenoha 

Thank you for opening an issue

To makes things clearer, I think the Composition API is well supported  (a lot of us are using it day to day), but maybe we can improve `script setup` support which is fairly new (out of experimental state since Vue 3.2).

Your issue is a bit long so maybe I'm missing key points in there, but let me try to give you some help:
- to provide a value, you can use `mount(Component, global: { provide: { parentType: 'something' })`.
- you can provide props with `mount(Component, props: { title: 'Some title'})`, and it works as expected
- `script setup` has a difference compared to Composition API, as the component is closed by default. If you want to modify data out of the component, you have to expose it (see the script setup RFC). But in your case, I would probably just rely on jest to do so (that's what I teach in my Vue ebook/training). With Jest you can provide the value you want for data and then check the template for its existence.

I hope this helps. If you have other questions, I think the best way would be to open a dedicated issue, with your component and a test example that fails to do what you want. We are very much looking for feedback, and we can probably improve a lot around script setup support, but we do need tangible code to understand the issue 😉

**Comment by cexbrayat** [comment] 2021-08-23 15:07
👍 We don't need your complete code: in fact it would be too hard to debug. Just open small issues with a component and a failing test in a github repo and we'll give you a hand.

1. I'm missing the point of what is not working here. A repro would help (I'm currently on vacation, so maybe my brain is a bit slow 😅)
2. If `data` is exposed with defineExpose, then you can use `wrapper.vm.data = 'something'` in your test.
3. Sure, you can open issues on specific examples you would want, or even PRs if you feel like it. We would be very happy to have help on this front!

**Comment by maelga** [comment] 2021-08-23 15:17
@Xenoha 

Lachlan Miller (@lmiller1990), one of the maintainer of Vue Test Utils, has published a very useful handbook for testing Vue 3 with Jest. His YouTube series is also excellent:

- https://lmiller1990.github.io/vue-testing-handbook/v3/
- https://www.youtube.com/watch?v=0lV4dVYOyBw&list=PLC2LZCNWKL9ahK1IoODqYxKu5aA9T5IOA

I personally find more answers there than in the official documentation.

**Comment by cexbrayat** [comment] 2021-08-23 15:35
Lachlan's material is top notch 👍 If I may, I can also point to my [ebook and online training](https://books.ninja-squad.com/vue) if you're looking for test examples (a few hundreds provided in the online training, testing pretty much every aspect of an application).

**Comment by Xenoha** [comment] 2021-08-23 16:40
As a start, the below fails and only renders the v-else div. Without going back to all my .vue components to add defineExpose methods just for testing purposes, how would I use jest to see the correct template behavior?

```
<template>
  <div v-if=hasContent>
    <div id="contentInfo"
    </div>
  </div>
  <div v-else>
    <div id="noContent">
    </div>
  </div>
</template>
```

```
<script setup>
import { ref, watchEffect, inject } from 'vue'

const type = inject('someType')
const hasContent = ref(false)

watchEffect(() => {
  if (type === 'content') hasContent.value = true;
});

<script>
```

```
describe('layout', () => {
  it('renders content layout',  () => {
    const wrapper = mount(Layout, global: { provide: { someType: 'content' } })
    expect(wrapper.find('#contentInfo').exists()).toBe(true) 
  })
})
```

**Comment by cexbrayat** [comment] 2021-08-23 18:13
This looks like an issue then, because at first sight, that seems correct.

Out of curiosity: if you try using "classic" Composition API, does it work? I have several tests doing the same thing without `script setup` and it should work fine.

If you want to go one step further, you can open a PR with a failing test (see this test for example that we have for inject/provide https://github.com/vuejs/vue-test-utils-next/blob/master/tests/mountingOptions/global.provides.spec.ts), and we'll take a look.

**Comment by lmiller1990** [comment] 2021-08-23 23:47
I am fairly sure the problem is we do not have great support for `<script setup>`. The RFC changed multiple times, so we just decided to wait until it was standardized before supporting it.

Now it's standardized, we can probably start to aggressively fix related bugs and support it. Considering it was experimental until a few weeks ago, I don't think the lack of support was unreasonable, but we should definitely make sure all the existing tests work with `<script setup>` as expected.

**Comment by lmiller1990** [comment] 2021-08-23 23:58
@Xenoha I tried the example in your first post (just copy pasted it into this code base) and it works as expected:

https://github.com/vuejs/vue-test-utils-next/commit/cd223f9ca4f737e9602fb3d6317da81480400957

**Comment by Xenoha** [comment] 2021-08-24 01:01
@lmiller1990 thanks for you review and your videos on the subject. They are what I reviewed as well as training for my team.

See below. Here is the component. It works with the defineExpose and changing it through `wrapper.vm.hasContent` but not without.

vue, vue/compiler-sfc: 3.2.2

Package.json -- Dev Deps
```
"devDependencies": {
		"@babel/core": "^7.14.8",
		"@babel/eslint-parser": "^7.14.7",
		"@babel/preset-env": "^7.14.8",
		"@vitejs/plugin-vue": "^1.2.3",
		"@vue/compiler-sfc": "^3.0.11",
		"@vue/test-utils": "^2.0.0-rc.10",
		"babel-jest": "^26.5.6",
		"eslint": "^7.2.0",
		"eslint-config-airbnb-base": "14.2.1",
		"eslint-import-resolver-alias": "^1.1.2",
		"eslint-plugin-import": "^2.22.1",
		"eslint-plugin-vue": "^7.0.0-beta.4",
		"identity-obj-proxy": "^3.0.0",
		"jest": "^26.5.6",
		"jest-transform-stub": "^2.0.0",
		"sass": "^1.29.0",
		"vite": "^2.3.6",
		"vite-plugin-windicss": "^0.15.10",
		"vue-eslint-parser": "^7.9.0",
		"vue-jest": "^5.0.0-alpha.10",
		"windicss": "^3.1.5"
	},
	"babel": {
		"presets": [
			[
				"@babel/preset-env",
				{
					"targets": {
						"node": "current"
					}
				}
			]
		]
	},
	"engines": {
		"node": "14"
	}
```

Jest config
```
module.exports = {
	moduleFileExtensions: [
		'js',
		'json',
		'vue',
	],
	moduleNameMapper: {
		'^@/(.*)$': '<rootDir>/src/$1',
	},
	testEnvironment: 'jsdom',
	transform: {
		'^.+\\.js$': 'babel-jest',
		'^.+\\.vue$': 'vue-jest',
		'.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$': 'jest-transform-stub',
	},
};
```


```
<template>
	<div
		v-if="hasContent"
		class="h-60 grid grid-cols-3 gap-2"
	>
		<div>
			<x-input
				v-model="computedName"
				name="name"
				label="Name"
			/>
			<x-textarea
				v-model="computedDescription"
				class="mt-5 w-full py-2"
				label="Description"
				rows="3"
			/>
			<x-input
				v-if="type === 'content'"
				v-model="computedDuration"
				:readonly="isReadonly"
				class="mt-3"
				name="duration"
				label="Duration"
			/>
		</div>
		<div
			id="contentInfo"
			class="mt-4 justify-self-center"
		>
			<div class="text-primary">
				File Name:
			</div>
			<div class="text-secondary ml-4">
				{{ fileName }}
			</div>
			<div class="text-primary">
				Aspect Ratio:
			</div>
			<div class="text-secondary ml-4">
				{{ aspectRatio }}
			</div>
			<div class="text-primary">
				MIME Type:
			</div>
			<div class="text-secondary ml-4">
				{{ mimeType }}
			</div>
		</div>
		<drag-and-drop
			v-if="type !== 'library'"
			class="justify-self-end"
			width-class="w-70"
		/>
	</div>
	<div
		v-else
		class="h-60 grid grid-cols-2 gap-2"
	>
		<div class="content-section">
			<x-input
				v-model="computedName"
				name="name"
				label="Name"
			/>
			<x-textarea
				v-model="computedDescription"
				class="mt-5 w-full py-2"
				label="Description"
				rows="3"
			/>
			<x-input
				v-if="type === 'content'"
				v-model="computedDuration"
				:readonly="isReadonly"
				class="mt-3"
				name="duration"
				label="Duration (secs)"
			/>
		</div>
		<drag-and-drop
			v-if="type !== 'library'"
			:mime-type="mimeType"
			class="justify-self-end"
			width-class="w-70"
		/>
	</div>
</template>

<script setup>
import {
	computed, inject, ref, watchEffect,
} from 'vue';
import XInput from '@/components/XInput.vue';
import XTextarea from '@/components/XTextarea.vue';
import DragAndDrop from '@/components/DragAndDrop.vue';

/* Injections */
const type = inject('assetType');
const description = inject('description');
const updateDescription = inject('updateDescription');
const thumbnailAsset = inject('thumbnailAsset');
const name = inject('name');
const updateName = inject('updateName');

/* State */
const hasContent = ref(false);
const fileName = ref('');
const aspectRatio = ref('');
const mimeType = ref('');

/* Set State */
let duration;
let updateDuration;
let isReadonly;
if (type === 'content') {
	duration = inject('duration');
	updateDuration = inject('updateDuration');
	isReadonly = inject('isDurationReadonly');
} else {
	isReadonly = false;
}

/* Effect */
watchEffect(() => {
	if (thumbnailAsset.value && type === 'content') {
		hasContent.value = true;
		fileName.value = thumbnailAsset.value.filename;
		aspectRatio.value = thumbnailAsset.value.assets[0].aspectRatio;
		mimeType.value = thumbnailAsset.value.assets[0].mimeType;
	}
});

/* Computed */
const computedDuration = computed({
	get() {
		if (type !== 'content') return null;
		return duration.value;
	},
	set(newDuration) {
		updateDuration(+newDuration);
	},
});

const computedName = computed({
	get() {
		return name.value;
	},
	set(newValue) {
		updateName(newValue);
	},
});

const computedDescription = computed({
	get() {
		return description.value;
	},
	set(newValue) {
		updateDescription(newValue);
	},
});

// eslint-disable-next-line no-undef
//defineExpose({ hasContent });
</script>
```

Factory.js
```
import { mount } from '@vue/test-utils';

function factory(component, props = {}, store = {}, provided = {}, mocks = {}, slots = {}) {
	return mount(component, {
		props,
		slots: {
			...slots,
		},
		global: {
			provide: {
				store,
				...provided,
			},
			mocks,
		},
	});
}

export default factory;
```

.spec.js -- please note that the first test runs just fine, but not the second. 

The ThumbnailAsset is an injected proxy, which I think is the underlying problem. Suggestions on providing proxies as if they are Vue.readonly() ?
```
import factory from '../Factory';
import StandardDialogLayout from '@/components/layouts/StandardDialogLayout.vue';
import DragAndDrop from '@/components/DragAndDrop.vue';

beforeEach(() => {
	// create teleport target
	const el = document.createElement('div');
	el.id = 'dialogs';
	document.body.appendChild(el);
});

afterEach(() => {
	document.body.outerHTML = '';
});

const mockUpdateDescription = jest.fn();
const mockUpdateName = jest.fn();
const mockUpdateSelectedFile = jest.fn();
const mockUpdateThumb = jest.fn();
const mockUpdateDuration = jest.fn();

describe('StandardDialogLayout', () => {
	it('Loads default', () => {
		const wrapper = factory(StandardDialogLayout, undefined, undefined, {
			assetType: 'screen',
			description: 'Test Description',
			updateDescription: mockUpdateDescription(),
			thumbnailAsset: '',
			updateSelectedFile: mockUpdateSelectedFile(),
			thumb: '',
			updateThumb: mockUpdateThumb(),
			name: 'Test Name',
			updateName: mockUpdateName(),
		});

		expect(wrapper.find('input[type=text]').exists()).toBe(true);
		expect(wrapper.find('textarea').exists()).toBe(true);
		expect(wrapper.findComponent(DragAndDrop).exists()).toBe(true);
	});

	it('Loads content type without content',  () => {
		const wrapper = factory(StandardDialogLayout, undefined, undefined, {
			assetType: 'content',
			description: 'Test Description',
			updateDescription: mockUpdateDescription(),
			thumbnailAsset: '',
			updateSelectedFile: mockUpdateSelectedFile(),
			thumb: '',
			updateThumb: mockUpdateThumb(),
			name: '',
			updateName: mockUpdateName(),
			duration: '',
			isDurationReadonly: false,
			updateDuration: mockUpdateDuration(),
			file: '',
			metadata: {},
		});

		const inputs = wrapper.findAll('input[type=text]');
		expect(inputs.length).toBe(2);
		const [nameInput, durationInput] = inputs;
		expect(nameInput.text()).toBe('');
		expect(durationInput.text()).toBe('');
		expect(wrapper.find('textarea').exists()).toBe(true);
		expect(wrapper.findComponent(DragAndDrop).exists()).toBe(true);
	});

	it('Loads content type with content', () => {
		const wrapper = factory(StandardDialogLayout, undefined, undefined, {
			assetType: 'content',
			description: 'Test Description',
			updateDescription: mockUpdateDescription(),
			thumbnailAsset: { filename: 'test.png', assets: [{ aspectRatio: '16:9', mimeType: 'image' }] },
			updateSelectedFile: mockUpdateSelectedFile(),
			thumb: '',
			updateThumb: mockUpdateThumb(),
			name: '',
			updateName: mockUpdateName(),
			duration: '',
			isDurationReadonly: false,
			updateDuration: mockUpdateDuration(),
			file: '',
			metadata: {},
		});

		const inputs = wrapper.findAll('input[type=text]');
		expect(inputs.length).toBe(2);
		const [nameInput, durationInput] = inputs;
		expect(nameInput.text()).toBe('');
		expect(durationInput.text()).toBe('');
		expect(wrapper.find('textarea').exists()).toBe(true);
		expect(wrapper.find('#contentInfo').exists()).toBe(false);
		expect(wrapper.findComponent(DragAndDrop).exists()).toBe(true);

		// data is set so that we have content
		// wrapper.vm.hasContent = true;
		// await nextTick();
		expect(wrapper.find('#contentInfo').exists()).toBe(true);
	});
});
```

**Comment by lmiller1990** [comment] 2021-08-24 01:44
This code will not run as is - there are many missing parts, `x-input`, `@/components/layouts/StandardDialogLayout.vue`, etc. It will take me quite some time to get this running locally.

It would be really useful if you could post a repository I could clone and run. I don't think you need to include the entire component - just a minimal example. 

If you can do that, I'd be happy to either verify there is a bug and fix it (which is generally pretty quick, since I know both the Vue and Test Utils internals really well) or help identify the problem in your code and send you a PR showing you how to fix it.

**Comment by Xenoha** [comment] 2021-08-24 01:49
@lmiller1990 I'll spend sometime in the near future to get you a suite to assist. I'll need to breakdown my issues and it will take some time. Bare with me.

**Comment by lmiller1990** [comment] 2021-08-24 04:07
No problem.

I don't see any immediately actionable issue here, so I will close this. Please make a new issue with your reproduction when you have it ready.

**Closed by lmiller1990** 2021-08-24 04:07 UTC
Labels: needs reproduction

**Comment by cexbrayat** [comment] 2021-08-24 06:04
@lmiller1990 Thanks for taking the time to look into it!

But you pushed these commits on master and they broke the build: I suspect this was not intended? Can you revert and open a PR so this can be properly reviewed (there is also an `allowJs` option added to the TS config that should be removed). Thanks!
