### ISSUE TITLE
Setup and defineProps

### ISSUE THREAD

**Issue by mgibas** [vuejs/vue-test-utils-next#862] opened 2021-08-12 14:00 UTC
I have a hard time testing components that use setup method (either in `<script>` or `<script setup>`) like that:
```vue
<script setup>
import { reactive } from 'vue'

defineProps({
  msg: String
})

const state = reactive({ count: 0 })
</script>
``` 

test:
```js
import { mount } from '@vue/test-utils'
import HelloWorld from '@/components/hello-world.vue'

test("hellow world", () => {
  const wrapper = mount(HelloWorld, {
    props: {
      msg: 'Hello world'
    }   
  })  

  expect(wrapper.vm.msg).toEqual('Hello world')
  expect(wrapper.vm.state.count).toEqual(0)
})
```

Component seems to be mounted properly, though there is no `vm.state.count` or `vm.msg` on it :( All of this works when I move these declarations outside of the setup:

```vue
<script>
export default {
  props: {
    msg: String
  },
  data () {
    return {
      count: 0
    }
  }
}
</script>
```

Am I missing something, like some extra call, await or something ?

Versions:
```
"vue": "^3.2.2"
"@vue/test-utils": "^2.0.0-rc.12"
"@vue/compiler-sfc": "^3.2.2"
```

**Comment by standbyoneself** [comment] 2021-08-12 21:19
When you use **Options API**, you can access your `data` and `methods`. Otherwise, when you use **Composition API**, e.g. `ref`, `reactive`, some functions defined inside `setup()`, you can't access these directly from `wrapper.vm`.

So if your component looks like this:
```vue
<script>
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'App',
  setup() {
    const someData = ref();

    const someMethod = () => {};

    return { someData, someMethod };
  }
});
</script>
```

You cannot access `wrapper.vm.someData`, `wrapper.vm.someMethod`.

*Small advice:*

*May be you need to rethink your testing approach. There is no need to test that props/state have some value, you need to test things closer to user interaction.
For example, pass some prop, find an element and assert that text value of this element equals to prop value. Or if you have a function, that makes some modal visible, just emit the click event, find the modal and assert that it is visible. 
Make some input and test the output.
Something like this.*

**Comment by mgibas** [comment] 2021-08-13 01:12
Thanks @standbyoneself!
Do you know if lack of support for Composition API is documented somewhere ?

Suggested advice is a big no-no for me (nonetheless thank you, really appreciate your time and effort to help) - I'm using vue-test-utils for my unit tests, and most of the time I want to assert that my code _controls_ state properly, not really interested in markups and all that integrational nature of it (I use cypress on that level, if needed). Now I wonder - is this a new direction that this tool is taking or just your personal opinion ? Again, hard time finding anything about that in docs (release candidate yet, so its probably understandable).

**Comment by standbyoneself** [comment] 2021-08-13 02:34
Okay, understand you. May be you want to use `defineExpose()` method that is included in @vue/compiler-sfc and requires no import inside `<script setup>`. Check out the example:

HelloWorld.vue
```vue
<template>
  <div class="hello-world"></div>
</template>

<script setup>
const someData = 'data';

const someMethod = () => console.log('something cool');

defineExpose({ someData, someMethod });
</script>
```

HelloWorld.spec.js
```js
import { shallowMount } from '@vue/test-utils';
import HelloWorld from '@/components/HelloWorld.vue';

describe('HelloWorld.vue', () => {
  it('does something cool', () => {
    const wrapper = shallowMount(HelloWorld);

    console.log(wrapper.vm);
  });
});
```

Outputs:

```
  HelloWorld.vue
    ✓ does something cool (8ms)

  console.log tests/unit/example.spec.js:8
    {
      someData: 'data',
      someMethod: [Function: someMethod],
      hasOwnProperty: [Function (anonymous)]
    }
```

Here the link to the docs: https://v3.vuejs.org/api/sfc-script-setup.html#defineexpose

**Comment by mgibas** [comment] 2021-08-13 11:19
@standbyoneself thanks a lot for that link (and even more for example!) - it makes much more sense now. I wasn’t aware that components defined with `<script setup>` are closed by design which would explain why vue-test-utils have no access to them.

Thanks again kind stranger!

**Comment by cexbrayat** [comment] 2021-08-23 08:14
Thanks @standbyoneself for helping here!

I just want to correct one statement if someone ends up here:

> When you use Options API, you can access your data and methods. Otherwise, when you use Composition API, e.g. ref, reactive, some functions defined inside setup(), you can't access these directly from wrapper.vm.

You _can_ access everything on `wrapper.vm` when using the Composition API (a lot of us are using this every day). But you can't if the component is using `script setup`, as the component is closed by design. You indeed have to expose what you want in that case 👍

**Comment by standbyoneself** [comment] 2021-08-23 08:28
@cexbrayat Hey there! Am I really wrong?

Hello.vue:
```vue
<template></template>

<script>
import { reactive, ref } from '@vue/reactivity';

export default {
  name: 'HelloWorld',
  setup() {
    const number = ref(123);

    const array = reactive([1, 2, 3]);

    const method = () => {};
  },
}
</script>
```

HelloWorld.spec.js:
```js
import { shallowMount } from '@vue/test-utils'
import HelloWorld from '@/components/HelloWorld.vue'

describe('HelloWorld.vue', () => {
  it('', () => {
    const wrapper = shallowMount(HelloWorld);

    console.log(wrapper.vm);
  });
});
```

Stdout:
```
HelloWorld.vue
  ✓  (8ms)

console.log tests/unit/HelloWorld.spec.js:8
  { hasOwnProperty: [Function (anonymous)] }
```

**Comment by cexbrayat** [comment] 2021-08-23 08:39
The `vm` represents the view model. So if they are returned to be used in the template (as it was the case in your previous example https://github.com/vuejs/vue-test-utils-next/issues/862#issuecomment-898129269), they are accessible on `wrapper.vm` yes 🙂

**Comment by standbyoneself** [comment] 2021-08-23 08:41
@cexbrayat Really. My bad. Thanks!

**Comment by axe-me** [comment] 2021-08-24 20:30
I knew the setup scirpt is closed by default and we need to use `defineExpose` macro to expose instance properties. But if I expose everything just for testing, it kinda defeats the purpose of the setup script that does not need to write the long return statement.

Just wondering if there is any workaround for VTU to expose everything by default just within testing scope.

**Comment by cexbrayat** [comment] 2021-08-25 06:41
@axe-me Agreed. Now that script setup is stable, we'll be able to take a look

**Closed** 2021-11-13 15:37 UTC
