### ISSUE TITLE
Error when mounting a renderless component with slots

### ISSUE THREAD

**Issue by adi518** [vuejs/vue-test-utils-next#576] opened 2021-05-08 12:27 UTC
### Subject of the issue

The test fails with `Cannot read property '$createElement' of undefined` when mounting a renderless component with a slot.

### Steps to reproduce

Run the following test:
```js
test('render with scoped-slot', async () => {
  const HelloWorld = {
    render() {
      return this.$slots.default()
    },
  }
  const wrapper = shallowMount(HelloWorld, {
    slots: {
      default() {
        return <div></div>
      },
    },
  })
  expect(wrapper.html()).toMatchSnapshot()
})
```

### Expected behavior

It should pass without errors.

### Actual behavior

It emits the following error:
```js
  ● Scope › render with scoped-slot

    TypeError: Cannot read property '$createElement' of undefined

      101 |       props: commonProps,
      102 |       slots: {
    > 103 |         default(props) {
          |                        ^
      104 |           scope = props
      105 |           return <div>{props.connected ? 'connected' : 'disconnected'}</div>
      106 |         },
```

### Possible Solution

I tried setting `$createElement` as a global in `jest-setup.js`, but to no avail:
```js
import { h } from 'vue'

global.$createElement = h
```

**Comment by adi518** [comment] 2021-05-11 12:04
TSX? did you mean JSX? I'm developing this component with Vite, so I simply used a Vite Vue template with some stuff added from a Vue CLI template to support tests, see: https://github.com/adi518/vue-facebook-login/blob/next/packages/vue-facebook-login-component-next/package.json.

**Comment by lmiller1990** [comment] 2021-05-12 00:59
TSX, JSX... same thing really :)

What I mean is we will need to update this code base to support working with JSX/TSX. The best way to get this fixed is something like:

1. add JSX/TSX support to this code base.
2. reproduce problem with a minimal test in this code base.  Create PR (failing is fine).
3. get the test green and passing.

I can work on this, but I also have many other things to work on. If this is a priority for you, the fastest way to get it fixed will be if you do the steps (1) and (2) and make a PR. If you aren't sure how to actually solve this issue here, that's fine, but having a minimal example and PR to work off will allow myself or someone else to pick it up.

**Comment by YutamaKotaro** [comment] 2021-05-26 14:16
I guess.. this is already not a bug, because I tried this test case and works well.
So, it's ok to close this issue, I wonder.

@adi518 If you'd like, please see this config for your test.
https://github.com/YutamaKotaro/vue-test-utils-next/commit/c9e99facef15bba175266bf4fe49ecee29786c75

If there is something wrong, I'm very sorry 🙇🏻

**Comment by adi518** [comment] 2021-05-26 14:53
@YutamaKotaro I'm not using TS for that project. Is there a Jest config I should use instead?

**Comment by YutamaKotaro** [comment] 2021-05-27 14:34
@adi518
I think you don't need anything, because I tried your test case on your repository and it worked well.

https://github.com/YutamaKotaro/vue-facebook-login/commit/8cb7d3651c07e3d2511c5a6a598c7369daed35c1

So, I don't know what is your issue. 
Do you still have the issue ??
Or have you tried re-install packages and run test ?

Sorry for not resolving issue quickly.

**Comment by lmiller1990** [comment] 2021-06-25 13:48
I cannot reproduce this either - I copy pasted the example from the OP into this code base and it works as expected: https://github.com/vuejs/vue-test-utils-next/pull/691

Going to close this one.

**Closed by lmiller1990** 2021-06-25 13:48 UTC
Labels: bug
