### ISSUE TITLE
`findComponent` helper returns different instances every time when called

### ISSUE THREAD

**Issue by raichev-dima** [vuejs/vue-test-utils-next#286] opened 2020-12-29 15:12 UTC
I'm using the `findComponent` helper and it returns different instances every time when it's called. I had a piece of code like this:
```js
    const instance = wrapper.findComponent({ name: 'ExampleComponent' }).vm

    expect(instance.value).toBe('someValue')

    await wrapper.setProps({ value: undefined })

    expect(instance.value).toBe('somehowChanedValue')
 ```
 
 With the following change everything's working:
 ```js
    let instance = wrapper.findComponent({ name: 'ExampleComponent' }).vm

    expect(instance.value).toBe('someValue')

    await wrapper.setProps({ value: undefined })

    instance = wrapper.findComponent({ name: 'ExampleComponent' }).vm

    expect(instance.value).toBe('somehowChangedValue')
 ```
 Such behavior looks a bit counterintuitive for me and I wonder if it's intended

**Comment by lmiller1990** [comment] 2020-12-30 01:43
I think this makes perfect sense, this is how the virtual dom architecture works, isn't it? You make a change, so it blows away the old component instance and replaces it with a new one.

**Comment by lmiller1990** [comment] 2020-12-31 04:27
I am fairly sure this is intended behavior - this is how Vue works. Unless someone can prove otherwise (entirely open to this, I could be misunderstanding) I am going to close this one as a "works as intended".

As a rule of thumb, you generally want to avoid relying on side effects (like mutating an object reference). Re-querying like you are doing is likely a better practice.

**Closed by lmiller1990** 2020-12-31 04:27 UTC
Labels: invalid, question
