### ISSUE TITLE
Failed to test the focus method of the checkbox component

### ISSUE THREAD

**Issue by liuzaijiang** [vuejs/vue-test-utils-next#624] opened 2021-05-28 02:16 UTC
test: 
```
test('focus method work', async () => {
    const checked = ref(true)
    const mockFn = jest.fn()
    const wrapper = mount({
      components: { IxCheckbox },
      template: `<ix-checkbox v-model:checked="checked" @focus="mockFn" />`,
      setup() {
        return { checked, mockFn }
      },
    })

    wrapper.getComponent(IxCheckbox).vm.focus()
    
    await flushPromises()

    expect(mockFn).toBeCalledTimes(1)
 })
```
version:  2.0.0-rc.6

The focus method calls the input native focus method.

**Comment by cexbrayat** [comment] 2021-05-28 10:29
Hi @liuzaijiang 
Can you share what IxCheckbox looks like?

**Comment by liuzaijiang** [comment] 2021-05-28 13:59
> Hi @liuzaijiang
> Can you share what IxCheckbox looks like?

https://github.com/IduxFE/idux/tree/main/packages/components/checkbox/src

**Comment by cexbrayat** [comment] 2021-06-01 09:31
One of the maintainers will take a look when we have some free time, and try to find what is the issue (if there is one). I probably won't be able to look into it in the next days.

If you want, you can give it a try, contributions are most welcome!
I usually start by adding a unit test to the codebase with a simple reproduction, then try to understand what's going on.
Sometimes the fix is fairly easy, and you can open a pull request that we'll gladly review.

**Comment by lmiller1990** [comment] 2021-06-01 11:00
We had something like this recently in VTU v1. Can you try using `attachTo`? See [here for more info](https://github.com/vuejs/vue-test-utils/commit/83aa823b5c2c230bded1f7dcf349166a05886262).

**Comment by liuzaijiang** [comment] 2021-06-01 12:57
@lmiller1990  tks！using attachTo

```
test('focus & blur method work', async () => {
    const focusFn = jest.fn()
    const blurFn = jest.fn()
    const wrapper = mount({
      components: { IxCheckbox },
      attachTo: '.ix-checkbox',
      template: `<ix-checkbox ref="component" @focus="focusFn" @blur="blurFn" />`,
      setup() {
        return { focusFn, blurFn }
      },
    }, { attachTo: 'body' })

    await wrapper.getComponent(IxCheckbox).vm.focus()

    expect(focusFn).toBeCalledTimes(1)

    await wrapper.getComponent(IxCheckbox).vm.blur()

    expect(blurFn).toBeCalledTimes(1)
  })
```

**Comment by lmiller1990** [comment] 2021-06-02 01:23
Did it work?

If it does, please close the issue :)

**Closed** 2021-06-02 01:24 UTC
