### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by herkulano** [vuejs/vue-test-utils-next#246] opened 2020-11-13 09:48 UTC
Get the following error in the render function when testing a component with a slot that renders another component:

`TypeError: Cannot read property 'replace' of undefined`

```ts
it('tests', () => {
  const wrapper = mount(ComponentX, {
    props: {
      label: 'Label',
    },
    slots: {
      default: h(ComponentY, { value: 'check' }),
    },
  })
})
```

The odd part is that it works in isolation, i.e., if we only run this test, but it doesn't work when we run all tests.

**Comment by afontcu** [comment] 2020-11-13 09:52
Hi!


> The odd part is that it works in isolation, i.e., if we only run this test, but it doesn't work when we run all tests.

Can you then share the additional context? Is it possible that you're sharing some sort of state between tests?

**Comment by herkulano** [comment] 2020-11-13 09:57
Here is the full test. Removed the assertions for simplicity.

```ts
describe('CompX', () => {
  it('is called', () => {
    const wrapper = shallowMount(CompX, {})
    expect(wrapper.exists()).toBeTruthy()
  })

  it('shows label and helper text', () => {
    const wrapper = shallowMount(CompX, {
      props: {
        label: 'Label',
        helperText: 'Helper text',
      },
    })
  })

  it('shows error text and hides helper text', () => {
    const wrapper = shallowMount(CompX, {
      props: {
        label: 'Label',
        helperText: 'Helper text',
        errorText: 'Error text',
      },
    })
  })

  it('connects label and input with same id', async () => {
    const wrapper = mount(CompX, {
      props: {
        label: 'Label',
        helperText: 'Helper text',
      },
      slots: {
        default: h(CompY, { value: 'check' }),
      },
    })
  })
})
```

**Comment by herkulano** [comment] 2020-11-13 12:16
Fixed by adding `name:` to the component 🤦

**Comment by herkulano** [comment] 2020-11-13 13:01
double 🤦 , forgot to remove `.skip` from the test!

Now the component becomes a stub, even though it's a `mount()`?
```html
<comp-y-stub></comp-y-stub>
```

From the docs, I think this shouldn't be the case, right?
https://vue-test-utils.vuejs.org/v2/guide/stubs-shallow-mount.html

**Comment by herkulano** [comment] 2020-11-13 13:04
I also tried using:
```ts
config.renderStubDefaultSlot = true
```

**Comment by lmiller1990** [comment] 2020-11-14 08:29
Thanks for the but report!

Can you please share `CompY`? Seems like a bug, we should not require `name`. If you are using `mount` nothing should be stubbed.

Could you post a full reproduction? What is `ComponentX`, `ComponentY`, etc. Ideally post a GitHub repository, and I can fix it.

**Comment by herkulano** [comment] 2020-11-15 10:22
## Input Component
```ts
<template>
  <input
    :id="uid"
    :class="classes"
    v-model="computedValue"
    @focus="onFocus"
    @blur="onBlur"
  />
</template>

<script lang="ts">
  import { computed, defineComponent, inject } from 'vue'
  import { uidProvider } from '@/components/Formfield/Formfield.vue'
  import './Input.scss'

  export default defineComponent({
    name: 'xx-input',
    props: {
      modelValue: [Number, String],
      invalid: Boolean,
      value: String,
    },

    setup(props, ctx) {
      const uid = inject(uidProvider, null)
      const classes = computed(() => ['xx-input', { invalid: props.invalid }])

      const computedValue = computed({
        get: () => props.modelValue ?? props.value,
        set: (val) => ctx.emit('update:modelValue', val),
      })

      function onFocus(e: Event) {
        ctx.emit('focus', e)
      }

      function onBlur(e: Event) {
        ctx.emit('blur', e)
      }

      return {
        uid,
        classes,
        computedValue,
        onFocus,
        onBlur,
      }
    },
  })
</script>
```

### Formfield Component
```ts
<template>
  <label v-if="label" :for="uid" class="xx-formfield-label">{{ label }}</label>
  <slot v-if="$slots.default" :id="uid" />
  <div v-if="info" :class="infoClasses">{{ info }}</div>
</template>

<script lang="ts">
  import { computed, defineComponent, provide } from 'vue'
  import { uid as uuid } from 'uid/single'
  import './Formfield.scss'

  export const uidProvider = 'uid'

  export default defineComponent({
    name: 'xx-formfield',
    props: {
      label: String,
      helperText: String,
      errorText: String,
    },

    setup(props) {
      const uid = `i-${uuid()}`
      provide(uidProvider, uid)

      const info = computed(() => {
        return props.errorText ?? props.helperText
      })
      const infoClasses = computed(() => ['xx-formfield-info', { error: props.errorText }])

      return {
        uid,
        info,
        infoClasses: infoClasses,
      }
    },
  })
</script>
```

## Formfield Component Test
```ts
import { config, mount, shallowMount } from '@vue/test-utils'
import { h } from 'vue'

import Formfield from './Formfield.vue'
import Input from '@/components/Input/Input.vue'

describe('Formfield', () => {
  it('is called', () => {
    const wrapper = shallowMount(Formfield, {})
    expect(wrapper.exists()).toBeTruthy()
  })

  it('shows label and helper text', () => {
    const wrapper = shallowMount(Formfield, {
      props: {
        label: 'Label',
        helperText: 'Helper text',
      },
    })
  })

  it('shows error text and hides helper text', () => {
    const wrapper = shallowMount(Formfield, {
      props: {
        label: 'Label',
        helperText: 'Helper text',
        errorText: 'Error text',
      },
    })
  })

  it('connects label and input with same id', async () => {
    const wrapper = mount(Formfield, {
      props: {
        label: 'Label',
        helperText: 'Helper text',
      },
      slots: {
        default: h(Input, { value: 'check' }),
      },
    })
  })
})
```

**Comment by afontcu** [comment] 2020-12-27 19:03
Hi! I might be mistaken, but I believe the issue is related to the way you're using the `slot` option when rendering the component.

Looks like Formfield component is using a scoped slot, so you should get the desired value from the slot and then pass it back to the component:

```js
    const wrapper = mount(Formfield, {
      global: {
        components: {
          Input  // Needed to make it available to the slot
        }
      },
      props: {
        label: 'Label',
        helperText: 'Helper text'
      },
      slots: {
        default: `<template #default="{ id }">
          <Input :value="id" /> 
        </template>`
      }
    })

```

---


That being said, I agree the error message is really cryptic and misleading. Not sure if we could improve it somehow…

**Comment by lmiller1990** [comment] 2020-12-28 02:00
I just ran the reproduction provided and everything is passing. Maybe this got fixed already? @herkulano can you confirm if you are still having this problem?

I will close this for now since as far as I can tell this is no longer a bug (all ✅ for me).

**Closed by lmiller1990** 2020-12-28 02:00 UTC
Labels: bug

**Comment by afontcu** [comment] 2020-12-28 08:18
> I just ran the reproduction provided and everything is passing. Maybe this got fixed already? @herkulano can you confirm if you are still having this problem?

If I recall correctly, reproduction fails if you remove `name` from Input component

**Comment by herkulano** [comment] 2020-12-28 12:29
@lmiller1990 it works now! ✅
