### ISSUE TITLE
Support `find({ ref })` syntax

### ISSUE THREAD

**Issue by kanryu** [vuejs/vue-test-utils-next#716] opened 2021-06-30 01:53 UTC
### Subject of the issue

Calling findComponent () with the ref method causes a run-time error.

### Steps to reproduce

```html
<template>
  <div class="hello">
    <h1>{{ msg }}</h1>
    <button ref="some_ref" v-on:click="$emit('accepted')">OK</button>
  </div>
</template>
```

```js
import { mount } from '@vue/test-utils';
import Component from '@/components/HelloWorld.vue'

describe('button-exists', () => {
    const wrapper = mount(Component)

    it('ref check', () => {
        const some_ref = wrapper.findComponent({ref: 'some_ref'})
        expect(some_ref.exists()).toBe(true)
    })
})
```

- write a template like the one above
- call `wrapper.findComponent({ref: 'some_ref'})`

### Expected behaviour

findComponent() should return a valid node.

### Actual behaviour

runtime error.

```
    TypeError: Cannot read property 'emits' of undefined

      42 |     it('ref check', () => {
      43 |         console.log(wrapper)
    > 44 |         const some_ref = wrapper.findComponent({ref: 'some_ref'})
         |                                    ^
      45 |         expect(some_ref.exists()).toBe(true)
      46 |     })
      47 | })

      at VueWrapper.Object.<anonymous>.VueWrapper.attachNativeEventListener (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7225:33)
      at new VueWrapper (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7202:15)
      at createWrapper (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7384:12)
      at VueWrapper.findComponent (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7305:24)
      at Object.<anonymous> (tests/App.spec.js:44:36)
```

### Possible Solution

I can't comment because I don't know the detailed implementation of this framework, but when I checked it with the debugger, `VueWrapper.prototype.attachNativeEventListener()` is executed twice.

The first time, `vm` points to a Proxy and it runs success.
The second time it points to a HTMLButtonElement and it doesn't have a `$options` property, which causes a run-time error.

### versions

- "vue": "^3.0.0"
- "core-js": "^3.6.5",
- "@vue/compiler-sfc": "^3.0.0",
- "@vue/component-compiler-utils": "^3.2.2",
- "@vue/test-utils": "^2.0.0-rc.9",
- "babel-jest": "<27",
- "jest": "<27",
- "vue-jest": "^5.0.0-alpha.10"

**Comment by xanf** [comment] 2021-06-30 06:59
The issue is that VTU is expecting `findComponent` result to always be a Vue instance, while your ref is assigned to HTML node

Since this is perfectly valid use case, I believe a perfect solution is to add assertion there and throw in case of such scenario as first step. After that allow `find({ ref : ... })` on DOMWrapper and VueWrapper (this will require some effort, but is closely related to PR I'm working on, which allows chaining find() + findComponent() calls)

**Comment by afontcu** [comment] 2021-06-30 07:02
Adding a user-friendly exception there sounds a good first step. @kanryu fancy to open up a PR? 🚀

**Comment by lmiller1990** [comment] 2021-07-08 09:42
I don't understand how this can be considered a valid use case. `findComponent` finds components, and in this case you the OP is trying to find a HTML node. This seems like the correct behavior. `find` for DOM nodes, `findComponent` for components.

**Comment by xanf** [comment] 2021-07-08 11:50
@lmiller1990 Sorry, I needed to explain my "perfectly valid use case" - I was meaning that "it is perfectly valid use case to assign ref to DOM node in Vue".

I totally support your position about error message and that `find({ ref: '' }` could be considered as "new" feature (it was available in VTU1)

**Comment by lmiller1990** [comment] 2021-07-09 00:13
I understand now - thanks.

I see two actions here:

1. fix this error message (this issue)
2. consider finding DOM nodes via ref (separate issue, not a fan of features for the sake of new features, but happy to consider if there's some use cases)

**Comment by mgdodge** [comment] 2021-08-11 20:22
@lmiller1990 , I see the PR for the first action item you mentioned has been merged and will probably be released soon. Any idea when the second option (finding DOM nodes via ref, like VTU1 did) will see traction? I have numerous unit tests written for Vue 2 that utilize refs on DOM nodes, and converting them to Vue 3 would be a lot smoother with just that one addition. The example used for this issue, rewritten with `find` instead of `findComponent` is exactly the use case I would imagine.

**Comment by lmiller1990** [comment] 2021-08-20 00:24
I think we could have this to help migration, but I don't think this should be a main feature or recommended way to query DOM nodes moving forward. I'd generally recommend things that work with `querySelector` (like `role`, `id`, `data-testid`, etc).

Unless you number of tests is truly staggering, it's probably just faster to change them all from `ref` to `data-testid` or something similar and move away from querying `ref`, than to wait for this to be supported. An alternative, if you want this *now*, would be to create a plugin: https://next.vue-test-utils.vuejs.org/guide/extending-vtu/plugins.html#plugins. All the DOM traversing logic is [here](https://github.com/vuejs/vue-test-utils-next/blob/master/src/utils/find.ts), we could expose some of the those functions if you need them. 

As for gaining traction, if enough people request the feature, we can definitely reconsider, but it seems like querying a DOM node by `ref` is tests not that common.

**Comment by robokozo** [comment] 2021-09-13 18:44
Personally, I think it would be really great to be able to find HTML elements by ref. I prefer this because I don't end up adding extra data to the dom (or my snapshot files) that are purely used for my unit testing purposes.

**Comment by frutsel32** [comment] 2021-09-15 09:52
I am currently working on migrating our project to vue 3 and have about 400 tests that fail because I can't find dom elements by ref. I would love for this to be re-added

**Comment by lmiller1990** [comment] 2021-09-21 01:19
While we figure out how to implement this in a way that covers all edge cases, I will try to provide a method you can use in the mean-time to help with migration.

**Comment by lmiller1990** [comment] 2021-11-04 00:46
Yes, https://github.com/vuejs/vue-test-utils-next/releases/tag/v2.0.0-rc.16 was released, `findComponent` now works with a DOM selector (again). Here is the PR: https://github.com/vuejs/vue-test-utils-next/pull/994.

I don't think we have support for `ref` yet, but does this help?

**Comment by mgdodge** [comment] 2021-11-06 16:40
Sorry for the somewhat-wordy response, but I want to make a few points.

Unfortunately, your reference to `findComponent` does not help much in what I am asking. `findComponent` is useful for finding _**components**_, but the original example listed here and referenced in my initial comment demonstrate finding _**standard HTML elements**_ using `ref`. If we were to replace `findComponent` with `find`, the problem of being unable to use a `ref` selector still exists. The example here is entirely valid, and matches my most common use case - refs on form inputs and buttons. The official Vue docs also include numerous examples - in fact, every example in their [template refs](https://v3.vuejs.org/guide/composition-api-template-refs.html#watching-template-refs) section has them on standard HTML elements. This omission from the current VTU seems a real step backward, since it worked fine in the previous Vue 2 version. 

I have always considered CSS selectors as being used for presentation, and if I really need a unit test to verify an element exists, assigning it a `ref` was a way of indicating that it had functionality important to the component being tested. I know that I could always add `data-testid`, but as @robokozo points out, why add a second attribute which ends up in the browser markup when we already have one assigned that is dedicated to Vue and doesn't pollute the markup at all?

Imagine scenarios like "Testing cancel and submit buttons in a modal" or "Testing input B when input A has a certain value"

- In both of scenarios, a standard button or input element is being looked for.
- Once I find the "submit button" or "input B", I might want to check if it is disabled or not.
  - Neither scenario has anything to do with what the element looks like.
- Now, consider another developer who comes along and removes CSS classes as part of a rebranding effort.
  - Changing the look of something should not break the unit test, if functionally in the browser they work just fine.
  - A developer working on styles alone wouldn't likely touch the `ref` attribute, so there's a measure of confidence/safety there.

One additional limitation I have encountered using CSS selectors comes up when using LESS as your CSS preprocessor. In the Vue 2 version using `<style lang="less" module>` results in a warning that LESS isn't processed in VTU, so none of the classes even make it into the tests. In this scenario, _you couldn't even start down the path of using CSS selectors_ to find things. I point this out because the suggestion to use CSS selectors to find HTML elements is not always going to be possible. Upgrading a component written with LESS modules and `ref` selectors will require changes that seem pointless.

I feel this should be re-added to core, but if that's not possible, a helper migration method would be amazing. A plugin would work as well, and I won't exclude that as a possibility. I do think, however, that the points I've made here illustrate that more thought needs to be given to a proper solution.

**Comment by lmiller1990** [comment] 2021-11-18 00:11
Right, I understand now - the original issue title and discussion were completely different. I changed the issue title. 

I forgot the context of why support for this was dropped. I can look into it again... if anyone else wants to speed things up, happy to help out with code review. Since we already have find by ref for `findComponent`, you can probably reuse a lot of that logic.

**Comment by lmiller1990** [comment] 2021-11-23 23:40
Coming in #1094

**Closed** 2021-11-29 07:10 UTC
Labels: bug

**Comment by kanryu** [comment] 2022-01-17 03:33
Thank you to everyone involved! :)

**Comment by ebisbe** [comment] 2024-12-11 07:59
@lmiller1990 I'm just asking here as it's related to what has been discussed on this PR but if you think it should be in a different place I'm ok. The description in the docs for https://test-utils.vuejs.org/api/#find is wrong as it's showing:
```
 wrapper.find({ ref: 'span' }) //=> found; returns DOMWrapper
 ```
 and it's not valid, right?
