### ISSUE TITLE
DomWrapper constructor requires second argument

### ISSUE THREAD

**Issue by nandi95** [vuejs/vue-test-utils-next#1101] opened 2021-11-23 18:14 UTC
After rc-17 the dom wrapper now requires a second argument: https://github.com/vuejs/vue-test-utils-next/commit/2700e88351fe9853288f974b9d0469f6084380d7#diff-3c1b58aba16a7a4e276820383e8816e322b620b2b20912542c257b467f02c25a however the package doesn't export this `typeof createWrapper`.
Can we have this exported? how should one construct a Dom wrapper around a non vm element?
Does this need new documentation?
The release has made no mention of this breaking change https://github.com/vuejs/vue-test-utils-next/releases/tag/v2.0.0-rc.17 maybe that should be updated too?

**Comment by lmiller1990** [comment] 2021-11-23 23:32
Oh, I didn't realize this would be breaking. I had to do this to remove a circular dependency.

We could make it nullable, I guess? The problem is we now support `findComponenr` etc on `DOMWrapper`, so the parent  `VueWrapper` is required. 

1. make the second arg nullable? Then we need appropriate error handling around when `VueWrapper` is null 
2. don't support creating a `DOMWrapper` (no idea what the use case is or why this is a thing)

**Comment by lmiller1990** [comment] 2021-11-23 23:40
Actually this might be undone and fixed here #1094

**Comment by nandi95** [comment] 2021-11-24 08:14
Yeah, I think anytime a signature of an exported functionality changes like this, it can be considered breaking.
The use case in my situation is:
```ts
const currentFocus = new DOMWrapper(document.activeElement!);
await currentFocus.trigger('keydown', { key: 'esc' });
```
Perhaps there's a better way of doing this?
I've tried:
```ts
document.activeElement.dispatchEvent(new KeyboardEvent('keydown', { key: 'esc' }));
await nextTick();
```
but that didn't work and I didn't investigate further

That PR seems to address this as the second argument is in fact removed from the dom wrapper.
Otherwise if that PR doesn't gets merged, nullable might be a solution, or perhaps the create wrapper can be exported and kinda mocked for these usecases? But it's possible there's another way to do the above and the DomWrapper doesn't need to be exported (apart from type maybe)

**Comment by lmiller1990** [comment] 2021-11-29 07:09
The PR is merged, I will release a new version of VTU soon, after merging  https://github.com/vuejs/vue-test-utils-next/pull/1110

**Comment by lmiller1990** [comment] 2021-12-24 02:15
rc-18 went out, this should be good now.

**Closed by lmiller1990** 2021-12-24 02:15 UTC
