### ISSUE TITLE
Vue Warn: Component emitted event customEvent but it is neither declared in the emits option...

### ISSUE THREAD

**Issue by brandonwoz** [vuejs/vue-test-utils-next#385] opened 2021-02-13 23:41 UTC
I saw issue [197](https://github.com/vuejs/vue-test-utils-next/issues/197), and the apparent fix. But I am getting this warning message still.

My set up is fairly simple: 

1. Parent component is shallow mounted. 
2. Child component is found via `wrapper.findComponent`.
3. Child component performs a `childComponent.vm.$emit('customEvent')`

And, the actual child component does have the custom event in the emits option.

Within the test, I tried setting the global.config.warnMessage's option to simply return if the message arg included the warning, but that didn't work. I also tried `childComponent.vm.$options.emits = ['customEvent'] `but it did not work either.

Any ideas?

**Comment by lmiller1990** [comment] 2021-02-14 23:41
What is `ChildComponent`? Can you share?

As long as it declares the `emits` key, it should be okay. It's possible a functional component is getting wrapped [here](https://github.com/vuejs/vue-test-utils-next/blob/9d3c2a6526f3d8751d29b2f9112ad2a3332bbf52/src/mount.ts#L234) and causing the problem.

Please provide a reproduction - it's impossible to help or even know if there is a problem otherwise.

**Comment by brandonwoz** [comment] 2021-02-15 00:16
Sorry about that...here is the reproduction.

```
**ChildCmp.vue**

<template>
  <div class="ChildCmp">
    <div class="ChildCmp__actions">
      <button
        type="button"
        @click="$emit('continue')">
        Continue
      </button>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'ChildCmp',

  emits: [ 'continue' ],
});
</script>




**ParentCmp.vue**

<template>
  <ChildCmp
    @continue="onContinue"
    @cancel="onCancel" />
</template>



 

**ParentCmp.spec.ts**

let wrapper: VueWrapper<any>;
describe('when ChildCmp emits "continue"', () => {
  beforeEach(() => {
    wrapper = factory();
    const childCmp = wrapper.findComponent('child-cmp-stub');
    childCmpt.vm.$emit('continue');
  });
  test('it should do something', () => {
    /** Test passes but Vue Warn is shown - [Vue warn]: Component emitted event "continue" but it is 
        neither declared in the emits option nor as an "onContinue" prop. */
  });
```

**Comment by lmiller1990** [comment] 2021-02-15 00:38
What happens if you do `wrapper.find('button').trigger('click')`?

Also what is `factory`? mount or shallow? What else does it do?

**Comment by brandonwoz** [comment] 2021-02-19 13:44
Factory simply` shallowMounts` the component. 

```
const factory = (overrides?: MountingOptions<{}>) => {
  const options: MountingOptions<{}> = {};
  return shallowMount(TheMap, mergeWith(options, overrides));
};
```

**Comment by lmiller1990** [comment] 2021-06-25 13:59
I guess this is now fixed - I could not reproduce:

![image](https://user-images.githubusercontent.com/19196536/123435827-555edb00-d611-11eb-8385-bc1d43e6811e.png)
 
Let me know if this is still a problem.

**Closed by lmiller1990** 2021-06-25 13:59 UTC
Labels: needs reproduction

**Comment by marvin-wtt** [comment] 2022-08-31 02:07
This error occurred to me as well. It happened when I changed the emit definition, but the page was only hot updated. After a complete reload, everything was fine.
