### ISSUE TITLE
Trigger doesn't work on a component with a renderless root component

### ISSUE THREAD

**Issue by adi518** [vuejs/vue-test-utils-next#577] opened 2021-05-09 00:35 UTC
I have a `FacebookLogin` component, which consists of a `Button` component and a `Scope` component. The `Scope` component doesn't render anything but its slot. On test, when I try to trigger a `click` event onto `FacebookLogin`, the event doesn't actually pass down to the Button component, resulting in a failed test.

`App.vue`
```html
<template>
	<FacebookLogin />
</template>
```

`FacebookLogin.vue`
```html
<template>
	<Scope>
		<Button />
	</Scope>
</template>
```

`FacebookLogin.spec.js`:
```js
test('login and click event', async () => {
  const onClick = jest.fn()
  const wrapper = mount(FacebookLogin, {
    attrs: { onClick },
  })
  await flush()
  await wrapper.trigger('click') // <-- point of failure
  await flush()
  expect(onClick).toHaveBeenCalledTimes(1)
  expect(wrapper.emitted().input.slice(-1)[0]).toEqual([
    {
      idle: true,
      error: null,
      hasError: false,
      enabled: true,
      working: false,
      disabled: false,
      connected: true,
      disconnected: false,
    },
  ])
})
```

Result:
```js
 FAIL  tests/unit/FacebookLogin.spec.js
  ● Button › login and click event

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 0

      72 |     await wrapper.trigger('click')
      73 |     await flush()
    > 74 |     expect(onClick).toHaveBeenCalledTimes(1)
         |                     ^
      75 |     expect(wrapper.emitted().input.slice(-1)[0]).toEqual([
      76 |       {
      77 |         idle: true,

      at Object.<anonymous> (tests/unit/FacebookLogin.spec.js:74:21)
```

**Comment by cexbrayat** [comment] 2021-05-10 14:51
Cool, that's what I was thinking. I don't see how it could work otherwise?
If you can provide a minimal reproduction we'll get a better understanding of what you expect. Otherwise, if you think it's enough, we'll close the issue.

**Comment by cexbrayat** [comment] 2021-05-11 06:33
I agree, I would test it like that as well.

@adi518 I'm going to close the issue, as It looks like it works as expected. Feel free to open another one if needed.

**Closed by cexbrayat** 2021-05-11 06:33 UTC

**Comment by adi518** [comment] 2021-05-11 11:53
> `find('button').trigger('click')` makes sense to me. `trigger` is for simualting DOM events - using it on a `VueWrapper` doesn't make a ton of sense to me.

But that's just circumventing the framework. It worked fine with Vue 2, so why not here?

**Comment by lmiller1990** [comment] 2021-05-11 14:57
Hm, this worked in VTU v1? We should match the behavior as much as possible.

One difference between Vue 2 and 3 is we now have components with multiple roots.

**Comment by lmiller1990** [comment] 2021-05-12 00:24
A minimal example should be:

```js
const Button = {
  template: `<button @click="handleClick" />`,
  methods: {
    handleClick() { this.$emit('click') }
  }
}

const Parent = {
  props: ['handleClick']
  components: { Button },
  template: `<Button @click="handleClick" />`
}

const handleClick = jest.fn()
mount(Parent, {
  props: { handleClick }
})

wrapper.trigger('click') 
```

Is this correct? You code base has a lot going on, I tried to extract out something simple so someone can work on this.

Basically the v1 behavior is something like "if wrapper has a root node and you call trigger, simulate that DOM event on the root node". In this case, because are using `mount`, the root node is `<button>` with the click event passed all the way down.
