### ISSUE TITLE
Cannot read property 'nextSibling' of null when wrapper.unmount

### ISSUE THREAD

**Issue by Jokcy** [vuejs/vue-test-utils-next#163] opened 2020-07-23 06:57 UTC
```ts
const Comp = defineComponent({
        setup(p: any, { slots }: any) {
          return () => slots.default && slots.default()
        }
      })

      const Demo = {
        setup() {
          return () => (
              <Comp>
                <MyComponent />
              </Comp>
          )
        }
      }

      const wrapper = mount(Demo)

      wrapper.unmount()
```

run this will cause: **Cannot read property 'nextSibling' of null**

but if I change Comp to 

```js
const Comp = defineComponent({
        setup(p: any, { slots }: any) {
          return () => h('div', slots.default && slots.default())
        }
      })
```

it works fine

**Comment by lmiller1990** [comment] 2020-07-23 11:12
Can you share repository where I can reproduce this? It looks like it's using JSX. Is JSX even stable with Vue yet 🤔 

I tried this out and it works fine for me. Your first example does give a warning:

```
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
      at <Anonymous>
      at <App ref="VTU_COMPONENT" >
      at <VTUROOT>
```

But it is still rendering correctly.

**Comment by lmiller1990** [comment] 2020-08-12 13:49
@Jokcy need a reproduction to debug this more. If you have one, please post it, and I will reopen this. Until then I cannot find the problem, so I'll close it off.

**Closed by lmiller1990** 2020-08-12 13:49 UTC
Labels: needs reproduction
