### ISSUE TITLE
setValue on select  input doesn't emit change event

### ISSUE THREAD

**Issue by alvarosaburido** [vuejs/vue-test-utils-next#281] opened 2020-12-22 10:44 UTC
Hi, I'm trying to test a wapper for a select  dropdown in vue 3 but for some reasons  `cmp.emmited()` is empty after setting a value:

```
let cmp;
  beforeEach(() => {
    cmp = mount(SelectInput, {
      props: {
        control: FieldControl({
          name: 'test-input',
          ...SelectField({
            label: 'Test Input',
            options: [
              {
                value: 'the-last-of-us',
                label: 'The Last of Us II',
              },
              {
                value: 'death-stranding',
                label: 'Death Stranding',
              },
              {
                value: 'nier-automata',
                label: 'Nier Automata',
              },
            ],
          }),
        }),
      },
    });
  });
test('emits an event when value changed', async () => {
    const select = cmp.find('select');
    await select.setValue('the-last-of-us');
    expect(cmp.emitted()).toHaveProperty('change');
    expect(emmited('change')[0][0].value).toBe('the-last-of-us');
    expect(emmited('change')[0][0].name).toBe('test-input');
  });
```

**Current behavior:**
`cmp.emitted()` is `{}`

<img width="1012" alt="Screenshot 2020-12-22 at 11 41 45" src="https://user-images.githubusercontent.com/4699008/102879816-b3381d80-444a-11eb-9671-1761bb5f1b47.png">

**Expected Behavior:** 
`cmp.emitted()` contains property `change`

**Version**
    "vue-jest": "^5.0.0-alpha.6",
  "@vue/test-utils": "^2.0.0-beta.10",
 "vue": "^3.0.0"

**Comment by lmiller1990** [comment] 2020-12-23 10:41
Impossible to say without a reproduction. What is `SelectField`?

Can you please post a repo I can run?

**Comment by lmiller1990** [comment] 2020-12-31 05:09
@alvarosaburido any chance of some more info here?

**Comment by alvarosaburido** [comment] 2020-12-31 11:31
I sorry, I hadn't time to create a repo, I will do it next year (bad joke) haha, I will create one as soon as I have some time

**Comment by lmiller1990** [comment] 2021-01-01 00:58
Sounds good. I will close the issue until then, since there is no way to triage it. Once you have a repro I can re-open it and help you solve it.

**Closed by lmiller1990** 2021-01-01 00:58 UTC
Labels: needs reproduction

**Comment by TheDutchCoder** [comment] 2021-03-03 21:49
I can confirm this does indeed not work. `setValue` does not change the value of a dropdown and also won't respond to `trigger('change')`.

I'll see if I can make a minimal repro for this, but for now this is what I can show:
```html
<template>
  <div>
    <select
      :selected="selected"
      :disabled="disabled"
      data-dropdown-select
      @change="onChange"
    >
      <option
        :disabled="placeholder.disabled"
        selected
      >
        {{ placeholder.label }}
      </option>
      <option
        v-for="option in options"
        :key="option.value"
        :value="option.value"
      >
        {{ option.label }}
      </option>
    </select>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType, computed } from 'vue'

export default defineComponent({
  name: 'ClDropdown',

  props: {
    options: {
      type: Array as PropType<Record<string, unknown>[]>,
      required: true,
    },

    placeholder: {
      type: Object as PropType<{label: string; disabled: boolean}>,
      default: () => ({
        label: 'please select', disabled: true,
      }),
    },

    selected: {
      type: [String, Number],
      default: '',
    },

    disabled: {
      type: Boolean,
      default: false,
    },
  },

  emits: ['update:selected'],

  setup (props, { emit }) {
    const onChange = (event: Event) => {
      emit('update:selected', (event.target as HTMLSelectElement).value)
    }

    return {
      onChange,
    }
  },

})
</script>
```

Test:
```js
import { mount, VueWrapper } from '@vue/test-utils'
import ClDropdown from '../dropdown.vue'

const options = [
  { label: 'Apples', value: 10 },
  { label: 'Pears', value: 20 },
  { label: 'Cherries', value: 30 },
]

let wrapper: VueWrapper<any>

describe('dropdown', () => {
  wrapper = mount(ClDropdown, {
    props: {
      options: options,
    },
  })

  it(`emits 'update:selected' event with correct values` , async () => {
    await wrapper.find('[data-dropdown-select]').setValue(20)
    await wrapper.find('[data-dropdown-select]').trigger('change')

    // change event won't be triggered, nor does the selected value change
  })
})
```
