### ISSUE TITLE
TypeScript compile error with 2.0.0-rc.14

### ISSUE THREAD

**Issue by tinobino** [vuejs/vue-test-utils-next#966] opened 2021-09-22 19:43 UTC
Hi!

When compiling my code via _vue-tsc_ I'm getting the following error:

```
node_modules/@vue/test-utils/dist/domWrapper.d.ts:5:28 - error TS2307: Cannot find module 'src' or its corresponding type declarations.

5 import { VueWrapper } from 'src';
                             ~~~~~
```

I think the import is wrong there.

**Comment by cexbrayat** [comment] 2021-09-23 06:59
Thank you for opening an issue.
This is a duplicate of #936 and it has already been fixed, but not yet released.

In the meantime check this comment for a workaround https://github.com/vuejs/vue-test-utils-next/issues/936#issuecomment-916844985

**Closed by cexbrayat** 2021-09-23 06:59 UTC
