### ISSUE TITLE
Feature request: Test against teleport element

### ISSUE THREAD

**Issue by JeremyWuuuuu** [vuejs/vue-test-utils-next#183] opened 2020-08-22 08:01 UTC
Hi, I've been trying to testing `Teleport` using `VTU` but I went through the code and I can not find any helper for testing teleported component, can we add a method to `vueWrapper` to find `teleported` children inside the component itself? I do 
believe this is something users would be constantly asking about.

## Requesting Feature
Test helper for `Teleport` API

## Current situation

We can only testing teleported element by raw document query.

**Comment by lmiller1990** [comment] 2020-08-25 11:27
If the feature you are designing requires the `<div class="showcase-class">` to be teleported to a specific element, I think the only real way to test this is to ensure it *is* actually rendered there.

You could use `attachTo` and create a method:

```js
function wasTeleportedTo(destination, content) {
  expect(document.querySelector(destination).outerHTML).toContain(content)
}
```

Or something.

I am not sure it makes sense to have something in VTU; all our API revolve around the idea of calling methods on a `wrapper`; I don't see a good way to implement something that fits this model.

I am still open to suggestions, do you have a proposal? This feels like a good use case for something like `testing-library` - its more focused on the big picture, where VTU focuses on a specific element. That, or just use a raw `document.querySelector` like you suggested. Again - open to suggestions/alternatives if you have a nice API in mind.

**Comment by lmiller1990** [comment] 2020-09-17 08:29
I am going to close this due to inactivity and no clear path forward. Happy to reopen if someone has a compelling proposal.

**Comment by nandi95** [comment] 2021-02-05 13:00
I'm currently working on a modal which is similar to @JeremyWuuuuu's example. Issue is I'm trying to assert that my modal renders the slot however, `wrapper.html()` only returns `<!--teleport start--><!--teleport end-->` therefore I can't work with any of the wrapper methods that makes this library great eg.: `find()`. Both the `wrapper.element` and `wrapper.vm.$el` are returning a `Comment {}` node. I can see that the element has been teleported when I inspect the `document.body`'s child elements.

It seems to me this shouldn't be a feature request but a bug report?
I'm not sure how to work around this currently while keeping the wrapper's functionality.

Perhaps we could have a new property on the `mount` method's argument called `teleportTarget` (string selector/ html element), and if defined the wrapper knows to not only work on the vm.$el but also look under the `teleportTarget`?
@lmiller1990

**Comment by lmiller1990** [comment] 2021-02-06 04:33
Can you post a minimal reproduction and the test you would like to write? I thought about it and we probably *should* have something for teleport.

**Comment by nandi95** [comment] 2021-02-06 09:20
@lmiller1990 

> It feels incorrect to call a method on `wrapper` that interacts with something outside the wrapper.

I'm not sure how I feel about that, on one hand you're right, on the other hand when you're using the teleport you also somewhat using your component in an "unexpeced" context.

I would avoid the helper methods that are not bound for the same reason I avoid the `DOMWrapper` solution if possible. As I outlined in the repo, that would force you to interact with the `VueWrapper` and see the result on the `DOMWrapper`

The repo: https://github.com/nandi95/VTU2-teleport-reproduction-repo/blob/main/src/components/Modal.test.ts

**Comment by lmiller1990** [comment] 2021-02-06 23:17
So we would just need to extend `find` etc to also include `teleportTarget` in the search if the `teleportTarget` mounting option is present? I am not sure I am clear on the proposal:

Regarding your proposal:
```html
<template>
  <teleport to="body">
    <div v-if="isVisible" style="background: red; padding: 20px">
      Header
      <slot></slot>
    </div>
  </teleport>
</template>
```

```js
it('should display the slot content', () => {
  const wrapper = mount(Modal, {
    slots: {
      default: '<div id="slot-content" />'
    },
    teleportTarget: document.body
})
```

What is the purpose of `teleportTarget`? To tell VTU where to look for the content? What happens if `teleportTarget` is set to something else (say, another element that does not exist). What is there is multiple `<teleport>` components?

At that point, it seems like it would make more sense to do what you originally suggested and find the `<teleport>` target, and include that in the search for `find`, etc, too. I have no idea if there is any technical limitations for this - are you interested in exploring an implementation?

**Comment by nandi95** [comment] 2021-02-06 23:59
> What is the purpose of teleportTarget? To tell VTU where to look for the content?

Yes.

> What happens if teleportTarget is set to something else (say, another element that does not exist).

I would say, throw an error. That's probably what Vue does too if it can't find the target when it encounters the teleport component.

> What is there is multiple <teleport> components?

Good question, is there some hack to get access to the teleport component? If so we could look at the `to` prop and find the target that would be grand (we wouldn't even need a new mounting option). Or otherwise `teleportTarget` can also be an array? In which you have to define every target, including teleports from child components.
Then maybe we can somehow concat the html of the targets. 

I haven't got experience with VTU's or vue's internals but I can certainly take a look.

**Comment by nandi95** [comment] 2021-02-07 14:46
@lmiller1990 
had a go with the `teleportTarget` mount option see the linked pr.
This is proving to be very messy and can have a lot of edge cases. It's not impossible to do though.
However before going down this road and polish up the PR and and handle same edge cases + add more tests I want to explore the option automating this teleport finding.
How I would do that can be seen here:
https://github.com/vuejs/vue-test-utils-next/pull/361/commits/777b6891e543a1149034e9371d7e486040c0de9d#diff-42896983e74b8984907fccce027becbca39cb25194ea08ec43835042682fb41bR158

**Comment by nandi95** [comment] 2021-02-08 12:58
I realised just now:
> that would force you to interact with the `VueWrapper` and see the result on the `DOMWrapper`

is already the case because find returns the DOMWrapper.
I just never really saved it to a variable.

Still I feel weird about an external `find` method. It would be clean if didn't had to import load of helper functions. However this is now the case with vue 3 eg.: `import { ref, computed, watch ... } from 'vue'` and it isn't too bad. So maybe a `find` method wouldn't be too bad after all?

**Comment by tbtalbottjr** [comment] 2021-02-23 17:55
I want to echo @lmiller1990's concerns about teleportTarget. I am "trying" to convert an app that uses the Element-Plus component library and am working through the test cases. Element-Plus has made a full rewrite based on VueJs 3.0 and has made liberal use of Teleport. The main examples I am running into are with el-dialog and el-dropdown. I have many test cases that test the contents of the these components since they tend to be dynamically generated, but now it is all hidden within the Teleport and I don't have access to that html anymore. Mostly, the Teleports seem to be attached to 'body' through their el-popper component. It would be great if there was a way to dynamically figure out where these Teleports went since I'm not always in control of that.

**Comment by nandi95** [comment] 2021-02-23 18:01
@tbtalbottjr This issue should probably be closed. Take a look at the linked PR: https://github.com/vuejs/vue-test-utils-next/pull/361 It had a way to dynamically figure out the target and test it as if the teleport didn't even happen, but the conclusion was that we should be using `new DomWrapper(document.querySeletor())`.

**Comment by tbtalbottjr** [comment] 2021-02-23 19:08
@nandi95 Thanks for the workaround. It looks like another option is to add a 'ref' to a component that is being teleported and using `outercomponent.findComponent({ ref: ref })`.

**Comment by lmiller1990** [comment] 2021-02-24 07:20
Let's close this - I opened https://github.com/vuejs/vue-test-utils-next/issues/418 in place of it.

**Closed by lmiller1990** 2021-02-24 07:20 UTC
Labels: enhancement
