### ISSUE TITLE
[Vue warn]: Property undefined was accessed during render but is not defined on instance. 

### ISSUE THREAD

**Issue by danranVm** [vuejs/vue-test-utils-next#549] opened 2021-04-26 03:43 UTC
```ts
  test('layout full page layout', () => {
    const Layout = {
      template: `
        <div>
          <header>
            <slot name="header" />
          </header>
    
          <main>
            <slot name="main" />
          </main>
          <footer>
            <slot name="footer" />
          </footer>
        </div>
      `,
    }
    const wrapper = mount(Layout, {
      slots: {
        header: '<div>Header</div>',
        main: '<div>Main Content</div>',
        footer: '<div>Footer</div>',
      },
    })

    expect(wrapper.html()).toContain('<div>Header</div>')
    expect(wrapper.html()).toContain('<div>Main Content</div>')
    expect(wrapper.html()).toContain('<div>Footer</div>')
  })
```

**Comment by lmiller1990** [comment] 2021-04-26 04:47
This should definitely work, I don't see any obvious problem. Will need to add this test to this code base and see what's going on.

**Comment by lmiller1990** [comment] 2021-04-26 04:50
I tried adding this to this code base - there is no problem, it's working fine. I'll need a full reproduction to investigate. Do you have other code in your code base?

I will close this for now since there is no problem, as far as I can tell. I can re-open if you provide more information with a reproduction.

**Comment by danranVm** [comment] 2021-04-26 07:35
@lmiller1990 hi, this warning appeared after I upgraded to the latest version today.

 minimal reproduction: https://github.com/danranVm/vue-test-utils-warn

**Comment by mengelbrecht** [comment] 2021-04-26 11:10
This happened for me too. A workaround is to use the `h` function instead of an html string:
```js
        const wrapper = mount(Layout, {
            slots: {
                header: h('div', {}, 'Header'),
                main: h('div', {}, 'Main Content'),
                footer: h('div', {}, 'Footer'),
            },
        })
```

**Comment by lmiller1990** [comment] 2021-04-27 00:43
Sounds like a regression. I will look at your repo. You should not need `h`.

**Comment by PeterAlfredLee** [comment] 2021-05-08 08:08
Hi @lmiller1990 , I think this warning is caused by this [compileSlots.ts#L18](https://github.com/vuejs/vue-test-utils-next/blob/master/src/utils/compileSlots.ts#L18):
```js
prefixIdentifiers: __BROWSER__
```
I just tested it, if you set `prefixIdentifiers` `true`, this warning won't show.

This is relate to #519, maybe we can find another way to solve #519, WDYT?

**Comment by lmiller1990** [comment] 2021-05-10 00:19
Interesting - you are probably correct. I think we only want that variable to be true in the iife build (for usage in a browser, like from a CDN). We should be able to mess around in [rollup.config.js](https://github.com/vuejs/vue-test-utils-next/blob/233ca806db022f78869241051a1f6187ae4abdbe/rollup.config.js#L34) to fix this.

**Comment by wujekbogdan** [comment] 2021-05-25 15:14
I don't think the issue is related to test utils. I'm experiencing a similar issue with a custom render function:

``` js
import { compile } from 'vue';

export default (name, props = {}) => ({
  inheritAttrs: false,
  name,
  props,
  setup() {
    // ... logic that builds the template string goes here
    const templateString = '<div><slot></slot></div>';
    return compile(templateString);
  },
});
```

In the console I'm getting:

```
[Vue warn]: Property undefined was accessed during render but is not defined on instance. 
  at <Container> 
  at <App>
```

It has something to do with slots, because as soon as I remove the slot from the template (`const templateString = '<div>I'm a div</div>';`) the warning goes away.

**Comment by lmiller1990** [comment] 2021-05-26 04:26
What do `compile` return? You generally need to return a function from `setup`, for example `return () => compile(templateString)`.

We have a test around the use case described in this issue, see here: https://github.com/vuejs/vue-test-utils-next/blob/279aa832a05191e113874a31cadff8a4cb424274/tests/mountingOptions/slots.spec.ts#L24.

I think this is an issue relating to configuration. This  code base uses `ts-jest` for the Jest preset, the OP reproduction uses `babel-jest`. I'm thinking this might be an issue in `vue-jest`.

**Comment by TheDutchCoder** [comment] 2021-06-04 20:07
I'm also seeing this issue, but with regular SFC's.

Example component:
```html
<template>
  <form data-form-wrapper-root>
    <slot />
  </form>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'ClFormWrapper',
})
</script>
```

Test:
```ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import { mount, VueWrapper } from '@vue/test-utils'
import ClFormWrapper from '#components/form/form-wrapper'

let wrapper: VueWrapper<any>

beforeEach(() => {
  wrapper = mount(ClFormWrapper, {
    slots: {
      default: '<div data-default-slot>Sample Content</div>',
    },
  })
})

afterEach(() => {
  wrapper.unmount()
})

describe('ClFormWrapper', () => {
  describe('defaults', () => {
    it('renders a FormWrapper', async () => {
      expect(wrapper.find('[data-form-wrapper-root]').exists()).toBe(true)
    })
  })
})
```

The tests pass, but there's a warning in the console:
```
    console.warn
      [Vue warn]: Property undefined was accessed during render but is not defined on instance.
        at <Anonymous >
        at <ClFormWrapper ref="VTU_COMPONENT" >
        at <VTUROOT>
```

**Comment by lmiller1990** [comment] 2021-06-07 00:56
@TheDutchCoder I copy pasted that exact code into the repo for this code base and I am not seeing the warning. Can you provide the version(s) and configuration you are using? Are you using babel-jest?

**Comment by TheDutchCoder** [comment] 2021-06-08 20:06
Hey @lmiller1990 
We're not using babel-jest, I'll list the version of related things though:
```
"@types/jest": "^26.0.23",
"@vue/test-utils": "^2.0.0-rc.6",
"jest": "^26.6.3",
"ts-jest": "^26.5.6",
"typescript": "^4.3.2",
"vue-jest": "^5.0.0-alpha.10",
"vue-loader": "^16.2.0",
```

This is the stack trace, it seems to have something to do with slots:
```
console.warn
      [Vue warn]: Property undefined was accessed during render but is not defined on instance.
        at <Anonymous >
        at <ClRadioGroup ref="VTU_COMPONENT" >
        at <VTUROOT>

      at warn (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:40:17)
      at Object.get (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6785:17)
      at Proxy.render (eval at processSlot (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:280:32), <anonymous>:11:64)
      at renderComponentRoot (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1157:44)
      at componentEffect (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5134:57)
      at reactiveEffect (node_modules/@vue/reactivity/dist/reactivity.cjs.js:46:24)
      at Object.effect (node_modules/@vue/reactivity/dist/reactivity.cjs.js:21:9)
      at setupRenderEffect (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5087:38)
```

**Comment by TheDutchCoder** [comment] 2021-06-08 20:13
To add: we narrowed it down to it really being an issue with slots.
Both default slots and named slots cause this issue to arise when testing. I looked at the source but I can't really see what the issue would be.

**Comment by lmiller1990** [comment] 2021-06-12 08:47
Fixed here: https://github.com/vuejs/vue-test-utils-next/pull/661

**Closed** 2021-06-13 11:42 UTC
